### ISSUE TITLE
Resolve versions with build metadata (plus sign)

### ISSUE THREAD

**Issue by PaulDeac** [FirelyTeam/Firely.Fhir.Packages#114]
According to SemVer a plus sign is allowed. (see documentation [here](https://semver.org/#spec-item-10)) 

However, it looks like the `Resolve()` function is ignoring the part of the version after the plus sign. 

The following unit test will reproduce the problem:
```c#
[Fact]
public void ResolveVersion_WithPlusSign_ShouldResolveToSameVersion()
{
    var version = "1.6.0+001";

    var versions = new Versions(["1.3.0", "1.6.0", version], []);

    var result = versions.Resolve(version, stable: false);

    Assert.Equal(version, result?.ToString());
}
``` 
Expected: "1.6.0+001"
Actual:   "1.6.0"

**Comment by mmsmits** [comment]
This seems to be an error of the SemanticVersioning library we use.

An issue has been filed:
https://github.com/adamreeve/semver.net/issues/64

**Comment by mmsmits** [comment]
@PaulDeac there was a reply to my change request saying that 1.6.0+x is considered the same version as 1.6.0.

>  Build metadata MUST be ignored when determining version precedence.

according to https://semver.org/spec/v2.0.0.html

So this is not a bug, but something our users need to consider I think.
What do you think?

@MatthijsvdWielen did this come from a customer support ticket?

**Comment by PaulDeac** [comment]
Hmm, this means that we will have to treat this case separately in Simplifier, at least when the user requests the build version explicitly. I'll discuss it internally with the team.

**Comment by mmsmits** [comment]
Or we educate our users on this semver rule.

**Comment by PaulDeac** [comment]
@mmsmits We fixed it in Simplifier so that when the user goes to a package page we first try to do an exact match on the version requested, only if we cannot find an exact match we do a resolve. 

However, I think I did found a bug. When you resolve `latest` it will resolve to a version with a build number if you specify `stable = false`. See the first unit test bellow. This is not correct, right?  

```C#
[Fact]
public void SemVerResolve_Latest_ShouldResolveToNonBuildVersion()
{
    var listed = new string[2] { "1.6.0", "1.6.0+001" };

    var result = new Versions(listed).Resolve(SemVer.LATEST, stable: false);

    Assert.Equal("1.6.0", result.ToString()); // fails
}

[Fact]
public void SemVerResolveStable_Latest_ShouldResolveToNonBuildVersion()
{
    var listed = new string[2] { "1.6.0", "1.6.0+001" };

    var result = new Versions(listed).Resolve(SemVer.LATEST, stable: true);

    Assert.Equal("1.6.0", result.ToString()); // works
}

[Fact]
public void SemVerResolve_BuildVersion_ShouldResolveToNonBuildVersion()
{
    var listed = new string[2] { "1.6.0", "1.6.0+001" };

    var result = new Versions(listed).Resolve("1.6.0+001", stable: false);

    Assert.Equal("1.6.0", result.ToString()); // works
}

[Fact]
public void SemVerResolveStable_BuildVersion_ShouldResolveToNonBuildVersion()
{
    var listed = new string[2] { "1.6.0", "1.6.0+001" };

    var result = new Versions(listed).Resolve("1.6.0+001", stable: true);

    Assert.Equal("1.6.0", result.ToString()); // works
}
```

**Comment by mmsmits** [comment]
Thanks Paul, I will check.

**Comment by mmsmits** [comment]
I don't think this is a bug:

```
[Fact]
public void SemVerResolve_Latest_ShouldResolveToNonBuildVersion()
{
    var listed = new string[2] { "1.6.0+001", "1.6.0" }; //<--- these are switched

    var result = new Versions(listed).Resolve(SemVer.LATEST, stable: false);

    Assert.Equal("1.6.0", result.ToString()); // works
}
```

When I switch around the versions like this in the listed List. The test works.
The SemVer library sees these two versions as the same version, also when sorting. So the one that's inputted after the other will be seen as the "latest" by the sorting algorithm. I think that's annoying, but according to the SemVer spec, they are considered the same version anyway.

**Comment by PaulDeac** [comment]
Right. Thanks!
