### ISSUE TITLE
Don't allow filenames with double dots in packages, for security

### ISSUE THREAD

**Issue by wardweistra** [FirelyTeam/Firely.Fhir.Packages#136]
Grahame once told me this is a security fix he was recommended to make: Don't allow files in packages with double dots in there. I guess to prevent attacks like these: https://en.wikipedia.org/wiki/Directory_traversal_attack

**Comment by alexzautke** [comment]
Already solved by https://github.com/FirelyTeam/Firely.Fhir.Packages/issues/47
