### ISSUE TITLE
Unpacking file containing '..' should be rejected

### ISSUE THREAD

**Issue by marcovisserFurore** [FirelyTeam/Firely.Fhir.Packages#47]
Any packages containing a file name that includes `..` should be rejected as suspicious. See also [this thread](https://chat.fhir.org/#narrow/stream/179239-tooling/topic/Security.20Issue.20in.20Packages) on Zulip.

**Comment by mmsmits** [comment]
We are not vulnerable for this. We use SharpZipLib to handle unpacking packages, they have fixed this issue in v1.0.0. We are using 1.3.3
