### ISSUE TITLE
[Package] Make some functions public again

### ISSUE THREAD

**Issue by mmsmits** [FirelyTeam/Firely.Fhir.Packages#53]
- [x] PackageClient.DownloadListingRawAsync()
- [x] JsonModelExtensions.AddDependency
- [x] PackageContect.Index => Lazy? Constructor?
- [x] Package.CreatePackage => default boolean moveToPackageFolder to true

**Comment by mharthoorn** [comment]
Also needed for FT:
1. DiskPackageCache.Resolve(PackageDependency dependency)
2.PackageContext.GetFileContent(PackageFileReference)
