### ISSUE TITLE
FHIR package client does not read detailed author information. 

### ISSUE THREAD

**Issue by MatthijsvdWielen** [FirelyTeam/Firely.Fhir.Packages#94]
Currently detailed author information in packages are not picked up, for example in Forge. The FHIR packages specification links to the NPM spec which indicates this should be possible: https://docs.npmjs.com/cli/v8/configuring-npm/package-json#people-fields-author-contributors

When a package.json contains an author with a name, Forge is unable to load a project. 

For example try the example author information from the NPM Spec:
 {

  "dependencies": {
    "hl7.fhir.r4.core": "4.0.1"
  },
  "fhirVersions": [
    "4.0.1"
  ],
  "author": {
    "name": "Barney Rubble",
    "email": "b@rubble.com",
    "url": "http://barnyrubble.tumblr.com/"
  }
}
 
Example package attached:
 
[package(1).json](https://github.com/FirelyTeam/firely-net-sdk/files/14108603/package.1.json)

**Comment by mmsmits** [comment]
Moved this to the package repo

**Comment by ewoutkramer** [comment]
I am pretty sure we read packages with unknown fields....there are 10s if not hundreds of fields (even ones from the FHIR NPM spec) that we do not parse I think!

**Comment by mmsmits** [comment]
Well I created this unit test:

```
  [TestMethod]
  public void TestUnknownProperties()
  {
      var json = File.ReadAllText($"TestData/unknown-properties-package.json");
      var manifest = PackageParser.ParseManifest(json);
      manifest.Should().NotBeNull();
  }
  ```

And that fails on unknown properties, so I think we don't. I'm just starting to investigate.

**Comment by mmsmits** [comment]
Ah, we do skip unknown properties, however, author is not unknown to us, We just treat it as a property instead of an object.
